### PR TITLE
feat(cluster/kube/builder): `"ram"` storage class

### PR DESCRIPTION
**Pull request by boz**
* Implement `"ram"` storage class with "empty dir" memory-backed volumes.
* No changes to resource accounting - service memory size must include size allocated to ram storage.

refs akash-network/support#179

### CODE REVIEW

**Comment by troian** [comment]
i'll cut node release [v0.30.2](https://github.com/akash-network/releases/v0.30.2) to fix tests

**Comment by boz** [comment]
just realized should include ram volume size when calculating price.

**Comment by boz** [comment]
should probably add validation for container's memory size in a few places.

**Comment by troian** [comment]
superseded by #217

**Pull request closed without merging**
